/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Music */

#ifndef _Included_Music
#define _Included_Music
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Music
 * Method:    load_jni
 * Signature: (Ljava/lang/String;LMusicFormat;)I
 */
JNIEXPORT jint JNICALL Java_Music_load_1jni
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
